default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mxy
  password: 123456
  host: localhost
  port: 5001

development:
  <<: *default
  database: morney_rails_development

test:
  <<: *default
  database: morney_rails_test

production:
  <<: *default
  database: morney_rails_production
  username: morney_rails
  password: <%= ENV['MORNEY_RAILS_DATABASE_PASSWORD'] %>
